OpenLiberty/liberty-tools-vscode

- README.md
- package.json
- src/extension.ts
- src/utils/Util.ts
- src/utils/devCommands.ts
- src/utils/libertyProject.ts
Support multi module project by:
- checking for boost runtime or liberty maven plugin in plugin management
- if the above exists, check and store modules listed in that pom
- check the other `pom.xml` files in the workspace and see if either their `artifactId` matches one of the previously stored modules or if they have the boost runtime or liberty maven plugin.
The plugin will display the parent `pom.xml`, modules of the parent `pom.xml`, and additional `pom.xml` files with the liberty maven plugin or boost runtime configured
> changed version and multi module support

- README.md
- package.json
- src/utils/Util.ts
- src/utils/devCommands.ts
- src/utils/libertyProject.ts
added support to honour `java.home` user setting with `liberty.terminal.useJavaHome`
Fix for https://github.com/OpenLiberty/liberty-dev-vscode-ext/issues/9
> liberty.terminal.useJavaHome introduced to use configured java.home

- package.json
Fix for #17 
Prevent the Liberty dev commands from showing up in the command palette, instead, they can only be triggered from the Liberty dev explorer view. 
> remove liberty.dev commands from command palette

- package.json
- src/utils/devCommands.ts
- src/utils/libertyProject.ts
Fix for #20
Improve the error message when a test report does not exist to make it clear to the user that they need to run tests to generate a report.
> update test report does not exist error message

- .gitignore
- README.md
- package.json
- src/extension.ts
- src/utils/GradleUtil.ts
- src/utils/MavenUtil.ts
- src/utils/Util.ts
- src/utils/devCommands.ts
- src/utils/libertyProject.ts
The extension will detect a liberty-gradle-project if:
1. `apply plugin: 'liberty'` and `io.openliberty.tools:liberty-gradle-plugin` is in the classpath in the `buildscript` block of the `build.gradle`
2. For multi-level projects, the plugin will list all subprojects in the `include` block of a parent's `settings.gradle` if the plugin is found in the `subprojects` or `allprojects` block of a parent's `build.gradle`. See #26.
In the explorer view of the dashboard, the project will either be named using the `rootProject.name=` setting in the `settings.gradle`, if that does not exist, it will be named after the directory name that the `build.gradle` is in.  The `settings.gradle` may be either in the same directory as the `build.gradle` or in a sub directory named `master`. 
For a multi-level …
> Add liberty-gradle-plugin support to the extension

- package.json
- src/extension.ts
- src/utils/GradleUtil.ts
- src/utils/MavenUtil.ts
Fix for #24 
Using a file watcher monitor `pom.xml`, `build.gradle` and `settings.gradle` files for modifications.  Prompt the Liberty Dev explorer view to refresh on detected changes.
> Refresh dev explorer view when files are modified/added/deleted

- src/extension.ts
- src/utils/devCommands.ts
- src/utils/libertyProject.ts
Fix for #32 
Track terminals that have been created and the projects they correspond to. When a terminal is closed, delete the corresponding terminal.
> Delete terminals when closed

- .eslintrc
Require semicolon and strict equality checks rules that were missed when moving to eslint
> Require semicolon

- package.json
- src/utils/GradleUtil.ts
- src/utils/devCommands.ts
- src/utils/libertyProject.ts
1. Reordered commands in dashboard so that they appear in logical order:
2. Changed logs and terminal name from `liberty:dev` to `liberty dev` so that it is not Maven specific.
3. Fixed typo in `getGradleProjectName` method
> Reordered commands in dashboard

- src/utils/GradleUtil.ts
- src/utils/constants.ts
- src/utils/devCommands.ts
Fix for #23 
Try to resolve custom test report locations.  If cannot resolve, search the workspace for `index.html` files that include `Test Summary`.  Use the most recently modified file.
If cannot find the above or there is not a custom test report location in the `build.gradle`, use the default `build/reports/tests/test/index.html`
> detect custom test report locations

- package.json
- src/extension.ts
- src/utils/GradleUtil.ts
- src/utils/MavenUtil.ts
- src/utils/buildFile.ts
- src/utils/constants.ts
- src/utils/devCommands.ts
- src/utils/libertyProject.ts
Fixes #64 
Adds `Start in container (tech preview)` command for projects with the Liberty Maven Plugin version 3.3-M1 and higher or Liberty Gradle Plugin version 3.1-M1 and higher.
If there is no version specified for the LMP in the `pom.xml`, assume that the latest version of the LMP is downloaded from maven central and display the dev mode in container option.
Note: versions not specified explicitly in the `pom.xml` or `build.gradle` (ie. in specified in a separate file, in a parent build file) will not be picked up and will not display dev mode in container option.
> Add start in container (tech preview) command

- README.md
- package-lock.json
- package.json
- src/liberty/devCommands.ts
Fixes #79 
If there is a value for the `maven.executable.path` setting, use this executable for Maven commands. Otherwise, if the `maven.executable.preferMavenWrapper` is true attempt to detect a `mvnw` file for the given `pom.xml` and use `mvnw`. Otherwise use `mvn`.
If the `java.import.gradle.wrapper.enabled` setting is true and we can detect a gradlew file in for the given `build.gradle`, Gradle commands will use `gradlew`, else will use `gradle`. 
> Use build tool wrappers when enabled

- gulpfile.js
- package.json
As long as the directory structure is:
- open-liberty-tools-vscode
- liberty-language-server
- lemminx-liberty
- liberty-ls
Running `npm run build` on the `open-liberty-tools-vscode` project will build the lemminx-liberty and liberty-ls projects and copy the jars into the `jars` directory
> build liberty-ls project with gulpfile

- .vscode/launch.json
- .vscode/settings.json
- CONTRIBUTING.md
- README.md
- package-lock.json
- src/extension.ts
- src/liberty/libertyProject.ts
This fixes the call `this._onDidChangeTreeData.fire()` which seems to now require an argument for the project to build properly.
Also:
- Refactored some code, and made some changes based on ES6 linter best practices.
- Fixed some old references and links.
- Added status bar icon to show the Liberty LS status: starting, started, or errored.
- Prepare Liberty LS for java debugging (something still doesn't work)
- Quality of life change to set VSCode language for JSON files to JSON with comments
- Commented out the npm:watch command in launch.json - it always errored and just added an extra click to run
> Fix launching liberty language server

- src/extension.ts
- src/liberty/libertyProject.ts
Added code to search for `server.xml` (`**/src/main/liberty/config/server.xml`) for folders that are not liberty project folders.
If a folder contains the above `server.xml` file, then will check if the root contains `pom.xml` or `build.gradle` and based on the findings the folder will be added to the new project map.
> fix #119 search for server.xml

- src/extension.ts
Small fix to run the language server only on `server.env` and `bootstrap.properties` files instead of all `.env` and `.properties` files.
When we determine the proper ways to detect if it is for a Liberty project, will update this. This may become a more involved process if they can be associated to Liberty by reference from another file.
> Narrow down files for LS to run on

- src/extension.ts
- src/util/requirements.ts
#154 
1) Properly forward the message.
2) Do not default to JRE used by `redhat.java`, as we have a more strict version check.
Included are the screenshots for an outdated Java version.
> fix java checks

- .vscodeignore
Before with gulpfile:
After without gulpfile:
> Exclude gulpfile from vsix file

- .github/workflows/build.yaml
- README.md
- gulpfile.js
- package.json
- `npm run build` now downloads LSP4Jakarta JDT and LS jars
- Removed LSP4Jakarta build step from GHA `build.yaml` 
- Updated `README.md` local build steps
Addresses #159 
> Pull lsp4jakarta jars from repo.eclipse.org

- src/extension.ts
- src/locales/en.json
- src/util/requirements.ts
#185 
A little tough to read in this screenshot, but`ps -ef | grep jar` reveals that the servers use RedHat's included JRE and the LemminX server starts with Java 11.
This is the warning received when the language servers continue functionality and LCLS lacks `*.xml` support.
- Requirements for resolve separately, 1) LemminX; 2) LSP4Jakarta and LCLS
- Server requirements checked reduced: 2 -> 1
- Refactored 
- LemminX checks:
- JAVA_HOME -> `xml.java.home` -> `java.home`
- LSP4Jakarta and LCLS
- RedHat JRE -> `java.jdt.ls.java.home` -> `java.home` -> JAVA_HOME
See issue for further information
> additional warning/check for LemminX Java Version

- CONTRIBUTING.md
- DEVELOPING.md
- README.md
See https://github.com/kathrynkodama/liberty-dev-vscode-ext/tree/readme-java17#liberty-tools-for-visual-studio-code and https://github.com/kathrynkodama/liberty-dev-vscode-ext/blob/readme-java17/CONTRIBUTING.md#contributing-to-liberty-dev-extension-for-visual-studio-code
Noting that on the next release, the Liberty Tools for VS Code page on the marketplace will reflect the changes made to the README.
> Clearly document Java 17 requirement

- package-lock.json
- package.json
Update LT version to 23.0.6-SNAPSHOT
Update VS Code minimum version to 1.78.0
> Update Liberty Tools and VS Code versions

- src/liberty/devCommands.ts
Fixed the issue - When executing the Liberty: Start... command from the command palette, the focus will redirect out into a terminal window when prompted the custom params.
> #210-fixed the issue Custom Start... command

- src/extension.ts
Client-side changes to support custom config files, enabled in OpenLiberty/liberty-language-server#212
- Send all .properties and .env files to LCLS
- Send fileChange events for .properties, .env, and liberty-plugin-config.xml to LCLS.
Tested that these changes do not affect how it currently works with the existing release of LCLS which does not support custom configs.
> Allow LCLS to handle custom config files

- src/definitions/lsp4jakartaLSRequestNames.ts
- src/extension.ts
there is a new "jakarta/java/fileInfo" message supported between LS and LSClient to get the package name for the file that is currently having a snippet inserted into it. This was not functioning in the vscode env because the config for that new message was missing from the DelegateCommandHandler and the vscode client config as well. Added this support so that package name can be obtained from the jakarta JDT LS extn. There is a separate PR int he liberty-tools-vscode repo to pick up the tool config side of this.
This PR cannot be merged/built until https://github.com/eclipse/lsp4jakarta/pull/501 is reviewed/merged and a lsp4jakarta snapshot is respun.
> add support for new jakarta LS/Client message - fileInfo

- package-lock.json
- package.json
- src/test/GradleTestDevModeActions.ts
- src/test/MavenTestDevModeActions.ts
- src/test/utils/testUtils.ts
Fixes #324 Enabled the vscode tests to work, enabled the clear command history at the end of gradle project tests to avoid receiving 'recently used' suggestions, and updated the version of the clipboardy component from 4.0.0 to 2.3.0.
>  Enable the vscode tests to work

- src/liberty/devCommands.ts
- src/test/MavenTestDevModeActions.ts
Fixes #340  , Fixes for report being created at a new location using the latest surefire plugin, now this checks the previous location as well as the new location for reports, also included test test cases for considering the new locations
> Fixes for report being created at a new location using the latest surefire plugin 

- src/definitions/constants.ts
- src/extension.ts
- src/liberty/dashboard.ts
- src/liberty/devCommands.ts
- src/liberty/libertyProject.ts
- src/locales/en.json
- src/util/helperUtil.ts
Fixes #264 Changes include the user being asked for saving the workspace when they try to add a project to the dashboard manually
> Fixes #264 - Fixes for manually added projects not being listed in the dashboard after re-opening IDE or workspace

- src/util/commandUtils.ts
Fixes #397 
Changes added for the command executing using mvn/gradle for windows - terminals cmd and poweshell
> Added fix for the start action for command using mvn/gradle 

- src/util/commandUtils.ts
Fixes #399 
Fix added for the command executing using gradle wrapper in mac
> Fix for gradle wrapper command - Project path with space

- src/util/commandUtils.ts
Fixes #413
Fix implemented for the command in the PowerShell terminal on Windows OS using Maven executable path.
> Fix added for the command in Powershell, Windows OS using maven executable path

- docs/user-guide.md
Also fixed the link for the "External extension settings" section.
> Document shell support in user guide

- CHANGELOG.md
Preview the changes here: https://github.com/TrevCraw/open-liberty-tools-vscode/blob/24.0.12-release-notes/CHANGELOG.md#24012
> Added release notes for 24.0.12

- src/test/GradleTestDevModeActions.ts
- src/test/MavenTestDevModeActions.ts
- src/test/utils/testUtils.ts
Fixes https://github.com/OpenLiberty/liberty-tools-vscode/issues/359
Fix for the message - getting displayed in logs after gradle test case execution.
> Updated message in logs - for gradle test case after execution

- src/test/resources/ci/scripts/exec.sh
Fixes #481 
Added method to fetch the status of previous command and update a boolean flag to see if the build is a failure or not.
Refer PR https://github.com/OpenLiberty/liberty-tools-vscode/pull/487 for more details.
> Issue 481 - Green Builds Showing Despite Test Failures

- gulpfile.js
- package.json
- src/extension.ts
Fixes #524 
Updated LSP4Jakarta 0.2.3 releases.
Tested the plugin and verified the [issue#389](https://github.com/OpenLiberty/liberty-tools-vscode/issues/389) with the new release version, and it is working as expected.
> Updated LSP4Jakarta 0.2.3 releases

- src/liberty/devCommands.ts
Fixes #534 
Clicking on (+) button in Liberty dashboard when there are no projects loaded in the IDE now results in the below error message toast, as would be expected:
```
No workspace folders are available to be added to the Liberty Dashboard.
```
https://github.com/user-attachments/assets/9167bc76-015e-4abc-ab36-307ed358268d
> Fix to check if uri is null
