OpenLiberty/liberty-tools-vscode

README.md, src/utils/libertyProject.ts
=> updated groupId of boost-maven-plugin

src/utils/libertyProject.ts
=> check profiles in pom for valid pom

package.json
=> updated version to 0.1.1

README.md
- Remove mention of boost although it still works
- Recommend liberty-maven-plugin version 3.1
=> Update description and version in readme

README.md, package.json
=> Change name to Open Liberty Tools

README.md
=> updated README description

package.json
=> update version and add category to commands for future use

src/extension.ts
=> fixed pomPaths to allPomPaths

src/extension.ts, src/utils/constants.ts, src/utils/devCommands.ts, src/utils/libertyProject.ts
=> Keep projects in memory in ProjectProvider

CHANGELOG.md, package.json, src/extension.ts
=> Refresh functionality to dashboard and add Changelog

package-lock.json, package.json
=> patch security issue with minimist

CHANGELOG.md, package.json
=> updated version to 0.1.7

CHANGELOG.md, README.md, package-lock.json, package.json
=> Mark Tools for MicroProfile as a dependency and bump version

.eslintrc, .gitignore, gulpfile.js, package-lock.json, package.json
Adds a build script to build lemminx-liberty.
Contributes it as a xml.extension in package.json
=> Contribute liberty lemminx extension to vscode-xml

package-lock.json, package.json
=> Update webpack dependency

package-lock.json
Re-generated `package-lock.json` to address security vulnerabilities 
=> Updated dependencies in package-lock.json

gulpfile.js, package.json, src/extension.ts
Depends on https://github.com/OpenLiberty/liberty-language-server/pull/53
=> Use updated jar names for Liberty language server deps

gulpfile.js
Needed after addition of Maven Invoker tests in https://github.com/OpenLiberty/liberty-language-server/pull/59
=> Skip invoker tests during build

src/liberty/libertyProject.ts
=> Fix event listener call

CHANGELOG.md, README.md, package-lock.json, package.json
=> Rename to Liberty Tools and bump version to 0.1.11

package-lock.json, package.json, src/util/gradleUtil.ts
Changed existing gradle script parsing code to handle both buildscript dependencies and plugin.
=> fix #111 parse gradle file

src/definitions/constants.ts, src/extension.ts, src/liberty/devCommands.ts, src/liberty/libertyProject.ts, src/test/runTest.ts, src/test/suite/extension.test.ts, src/test/suite/index.ts, src/util/buildFile.ts, src/util/gradleUtil.ts, src/util/helperUtil.ts, src/util/i18nUtil.ts, src/util/mavenUtil.ts
=> Add copyright headers to TS files

src/extension.ts, src/liberty/dashboard.ts, src/liberty/devCommands.ts, src/liberty/libertyProject.ts, src/liberty/projectStartCmdParam.ts, src/util/helperUtil.ts
Save custom start command params.
=> fixes #129 custom start command history

README.md, gulpfile.js, package.json, src/definitions/lsp4jakartaLSRequestNames.ts, src/extension.ts, src/locales/en.json, src/util/javaServerMode.ts
- add build to gulp
- add jakartajdt to java
- exec jakarta ls and bind requests
- init server mode
=> vscode for lsp4jakarta consumption

package-lock.json, package.json
=> Add the jdt ls ext for lsp4jakarta, fix

src/liberty/devCommands.ts
=> comment out error check

.github/workflows/build.yaml, CONTRIBUTING.md, README.md
Add github actions build
Update documentation to use "Visual Studio Code" instead of "VS Code"
=> Add github actions build

package.json, package.nls.json, src/definitions/constants.ts, src/extension.ts, src/liberty/devCommands.ts, src/locales/en.json, src/util/i18nUtil.ts
See #114 for updated design and screenshot.
Thanks
=> fix #114 hotkey to show list of commands

package.nls.json
=> Small capitalization fix

gulpfile.js
=> Fix Eclipse repo URL in gulpfile

gulpfile.js
=> Update liberty-langserver and liberty-langserver-lemminx versions

CHANGELOG.md
Updated plugin description to readme is in #209 
=> Add changelog for 0.1.12

gulpfile.js
=> Update jakarta.jdt artifact URL

package-lock.json, src/extension.ts, src/util/javaServerStarter.ts
Added some comments to debug the Liberty Config LS, see https://github.com/OpenLiberty/liberty-language-server/compare/main...kathrynkodama:debug-config?expand=1
Left the original debug TODO in the code, as I `process.env.SUSPEND_SERVER` is not implemented.
=> Params for debugging the Liberty LS

gulpfile.js, package.json, src/extension.ts
Changes for https://github.com/OpenLiberty/liberty-tools-vscode/issues/245
=> Pull in LCLS 2.0-SNAPSHOT

src/definitions/lsp4jakartaLSRequestNames.ts, src/extension.ts
Integrate change to lsp4jakarta.
Fixes #252
=> Add definition of Java cursor context message.

package-lock.json, package.json, src/extension.ts, src/util/javaServerStarter.ts
=> 247 code action cancel failures

DEVELOPING.md, package.json
Change the name of the command to build LCLS so it is not easily confused with step 6.
Do we need a reviewer from LCLS?
=> Update the build instructions to make it clear to run step 6. 

src/liberty/libertyProject.ts
=> #177 Liberty Explorer Refresh Button Issue

src/liberty/libertyProject.ts
Added full path of the pom.xml file (or build.gradle file) for the project  when you hover over the entry.
=> #208-Hover-FixIssue

gulpfile.js, package.json, src/extension.ts
=> Update lcls to v2.0.1

gulpfile.js, package.json, src/extension.ts
Fixes #294 
Added 2.1-SNAPSHOT version of the Liberty Config Language Server
=> Add 2.1-SNAPSHOT version of the Liberty Config Language Server

NOTICE
Update NOTICE file for 23.0.12 + convert to regular text file
=> Notice file 23.0.12

gulpfile.js, package.json, src/extension.ts
Fixes #342 
Updated the LCLS version to 2.2 releases
=> updated LCLS version to 2.2 releases

package.json
Fixes #382 , updated JsonPath-plus version to 10.2.0
=> Updated verison for JsonPath-plus to 10.2.0

gulpfile.js, package.json, src/extension.ts
part of #361 Updated the lcls version to 2.2-snapshot and release level as "snapshot".
=> Integration of lsp4jakarta v0.2.2-snapshot

package-lock.json, package.json
=> Issue451 - update vscode extension tester to latest version 8.10.0

src/test/resources/ci/scripts/setup.sh
=> Update kernel parameter for openResources() method to work in Ubuntu 24.04

.github/workflows/run-regression-tests.yml
=> Bumping upload-artifact to 4.3.4

src/test/GradleInitProject.ts, src/test/GradleTestDevModeActions.ts, src/test/MavenInitProject.ts, src/test/MavenTestDevModeActions.ts, src/test/utils/macUtils.ts, src/test/utils/testUtils.ts
=> Add copyright headers in files.

gulpfile.js, package.json, src/extension.ts
Fixes #523 
Updated the LCLS version to 2.2.1 releases 
Tested the plugin against the issues mentioned [here](https://github.com/OpenLiberty/liberty-tools-intellij/issues/1262) and all of them are working as expected.
=> Updated LCLS version to 2.2.1 releases 

package-lock.json, package.json
=> Update to 25.0.6-SNAPSHOT

package-lock.json, package.json, src/liberty/devCommands.ts, tsconfig.json
- Added the `projectName` property to the debugger launch config in `attachDebugger` in `devUtils.ts`
- Uses the label from the Liberty project as the value
Fixes #544
=> Add projectName property to debugger launch config

src/extension.ts
=> Update LCLS version to 2.3.1 in extension.ts

package-lock.json, package.json, src/definitions/constants.ts, src/definitions/lsp4jakartaLSRequestNames.ts, src/extension.ts, src/liberty/baseLibertyProject.ts, src/liberty/dashboard.ts, src/liberty/devCommands.ts, src/liberty/libertyProject.ts, src/liberty/projectStartCmdParam.ts, src/test/GradleInitProject.ts, src/test/GradleTestDevModeActions.ts, src/test/MavenInitProject.ts, src/test/MavenTestDevModeActions.ts, src/test/definitions/constants.ts, src/test/utils/macUtils.ts, src/test/utils/testUtils.ts, src/util/buildFile.ts, src/util/commandUtils.ts, src/util/gradleUtil.ts, src/util/helperUtil.ts, src/util/i18nUtil.ts, src/util/mavenUtil.ts
- Update IBM Copyright format
- Fix dependency CVE found by Mend
=> IBM Copyright Updates
